# Generated by Django 3.0.3 on 2020-02-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canada_adv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
