# Generated by Django 3.0.3 on 2020-02-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canada_adv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='food',
            new_name='user_food',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='water',
            new_name='user_water',
        ),
    ]
