# Generated by Django 3.0.3 on 2020-03-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canada_adv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='food_available',
            new_name='food_available_1',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='water_available',
            new_name='water_available_1',
        ),
    ]
