# Generated by Django 3.0.3 on 2020-02-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canada_adv', '0002_auto_20200225_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='user_id',
        ),
    ]
