# Generated by Django 3.0.3 on 2020-03-04 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canada_adv', '0002_auto_20200303_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserData',
        ),
    ]
