# Generated by Django 3.0.3 on 2020-02-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canada_adv', '0003_auto_20200225_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
